on:
  push:
    tags:
      - "**"

name: Create CLI Release

jobs:      
  cut_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.ref }}
          release_name: Release V${{ github.ref }}
